<?php

namespace AppBundle\Repository;

/**
 * CompanyInfosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyInfosRepository extends \Doctrine\ORM\EntityRepository
{
}
