<?php

namespace AppBundle\Repository;

/**
 * CompanyConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyConfigRepository extends \Doctrine\ORM\EntityRepository
{
}
