<?php

namespace AppBundle\Repository;

/**
 * ExpirationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpirationRepository extends \Doctrine\ORM\EntityRepository
{
}
