<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\BrowserKit\Response;

/**
 * MachineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MachineRepository extends EntityRepository
{
    public function machineByDep($depId){
        $tabMac = array();
        $macs = $this->_em->getRepository("AppBundle:Machine")->findAll();
        foreach ($macs as $mac){
            $dep = $mac->getDepartements();
            foreach ($dep as $d){
                if ($d->getId() == $depId){
                    if(!in_array($mac->getMachineId(),$tabMac,true)){
                        array_push($tabMac,$mac->getMachineId());
                    }
                }
            }

        }

        /*$queryBuilder = $this->createQueryBuilder('m');
        $queryBuilder->where('m.departements=:depId');
        $queryBuilder->setParameter('depId',$depId);*/

        return $tabMac;
    }
}
