<?php

namespace AppBundle\Repository;

/**
 * NullDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NullDateRepository extends \Doctrine\ORM\EntityRepository
{
    public function dayIsNull($date){
        $queryBuilder = $this->createQueryBuilder('n');
        $queryBuilder->where('n.jour = :date');
        $queryBuilder->setParameter('date',$date);

        $result = $queryBuilder->getQuery()->getResult();
        if($result != null){
            return true;
        }else{
            return false;
        }
    }

}
