<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WorkingHoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkingHoursRepository extends EntityRepository
{
    public function safeWorkingHour(){
        $qb = $this->createQueryBuilder('w');
        $qb->where('w.code != :code');
        $qb->setParameter('code',"Default");

        return $qb->getQuery()->getResult();
    }
}
