
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#tmye_device:
#    resource: "@TmyeDeviceBundle/Resources/config/routing.yml"
#    prefix:   /

tmye_device_annotation:
    resource: "@TmyeDeviceBundle/Controller"
    type:     annotation

login:
    path: /login
    defaults:
        _controller: UserBundle:Security:login
login_check:
    path: /login_check
logout:
    path: /logout

api_login_check:
    path: /api/login_check

app.swagger_ui:
    path: /api/doc/v1
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api/doc/v1/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }