
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#tmye_device:
#    resource: "@TmyeDeviceBundle/Resources/config/routing.yml"
#    prefix:   /

tmye_device_annotation:
    resource: "@TmyeDeviceBundle/Controller"
    type:     annotation

login:
    path: /login
    defaults:
        _controller: UserBundle:Security:login
login_check:
    path: /login_check
logout:
    path: /logout

api_login_check:
    path: /api/login_check