tmye_device:
    resource: "@TmyeDeviceBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
login:
    path: /login
    defaults:
        _controller: UserBundle:Security:login
login_check:
    path: /login_check
logout:
    path: /logout