# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\Employe:
            algorithm:   md5
            iterations: 1
            encode_as_base64: false
        AppBundle\Entity\Admin:
            algorithm:   md5
            iterations: 1
            encode_as_base64: false
        #Symfony\Component\Security\Core\User\User: sha512

    role_hierarchy:
            ROLE_SECRET: ROLE_USER
            ROLE_ADMIN_CONTROL: ROLE_SECRET
            ROLE_ADMIN: ROLE_ADMIN_CONTROL
            ROLE_SUPER_ADMIN: ROLE_ADMIN

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
      chain_provider:
        chain:
            providers: [main_employee,main_admin]
      main_employee:
        entity:
          class:    AppBundle\Entity\Employe
          property: username
      main_admin:
        entity:
          class:    AppBundle\Entity\Admin
          property: username
      jwt:
        lexik_jwt: ~
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
          pattern: ^/(_(profiler|wdt)|css|images|js)/
          security: false

        login:
          pattern: ^/api/login
          stateless: true
          anonymous: true
          json_login:
            provider: chain_provider
            check_path: /api/login_check
            success_handler: lexik_jwt_authentication.handler.authentication_success
            failure_handler: lexik_jwt_authentication.handler.authentication_failure
            require_previous_session: false

        api:
          pattern: ^/api/v1/
          stateless: true
          guard:
            authenticators:
              - lexik_jwt_authentication.jwt_token_authenticator
          provider: jwt

        main:
          pattern: ^/
          anonymous: true
          provider: chain_provider
          form_login:
            login_path: login
            check_path: login_check
          logout:
            path: logout
            target: login

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/api/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/api/v1,       roles: IS_AUTHENTICATED_FULLY}