# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app_bundle_expired:
        class: AppBundle\MyServices\Expiry
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    stats_controller:
        class: AppBundle\Controller\StatsController