<?php

namespace Tmye\DeviceBundle\Repository;

/**
 * ConfigEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
