<?php

namespace Tmye\DeviceBundle\Repository;

/**
 * RequestBlobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestBlobRepository extends \Doctrine\ORM\EntityRepository
{
}
