<?php

namespace TmyeDeviceBundle\Repository;

/**
 * DevicePubPicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DevicePubPicRepository extends \Doctrine\ORM\EntityRepository
{
}
