<?php

namespace TmyeDeviceBundle\Repository;

/**
 * DevicePubPicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoorEntityRepository extends \Doctrine\ORM\EntityRepository
{

    public function deviceByArray($devices){
        $i=0;
        $queryBuilder = $this->createQueryBuilder('d');
        $queryBuilder->where('d.device_id=:fId');
        $queryBuilder->setParameter('fId',$devices[0]);
        foreach ($devices as $devId){
            $i++;
            $queryBuilder->orWhere('d.device_id=:id'.$i);
            $queryBuilder->setParameter('id'.$i,$devId);
        }

        return $queryBuilder->getQuery()->getResult();
    }
}
