<?php

namespace TmyeDeviceBundle\Repository;

/**
 * AdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UpdateEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
