<?php

namespace TmyeDeviceBundle\Repository;

/**
 * AdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UpdateEntityRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByMachine($mac){
        $queryBuilder = $this->createQueryBuilder('u');
        $queryBuilder->where('u.deviceId = :deviceId');
        $queryBuilder->setParameter('deviceId',$mac);

        return $queryBuilder->getQuery()->getResult();
    }
}
